import type { RoadmapData } from "./types";

export const roadmapData: RoadmapData = {
  topics: [
    {
      id: "internet-web-fundamentals",
      title: "Internet & Web Fundamentals",
      description: "Understanding how the internet and web technologies work",
      order: 1,
      subtopics: [],
    },
    {
      id: "html",
      title: "HTML",
      description: "HyperText Markup Language - the foundation of web pages",
      order: 2,
      subtopics: [
        {
          id: "html-semantic",
          title: "Semantic HTML",
          description: "Learn to use semantic HTML elements for better structure and accessibility",
          order: 1,
          prerequisites: [],
          resources: [
            {
              type: "link",
              title: "MDN: HTML Semantics",
              url: "https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantic_elements",
            },
          ],
          estimatedTime: "1 hour",
          difficulty: "beginner",
        },
        {
          id: "html-forms",
          title: "Forms & Inputs",
          description: "Master HTML form elements and input types",
          order: 2,
          prerequisites: ["html-semantic"],
          resources: [
            {
              type: "link",
              title: "MDN: HTML Forms",
              url: "https://developer.mozilla.org/en-US/docs/Learn/Forms",
            },
          ],
          estimatedTime: "2 hours",
          difficulty: "beginner",
        },
      ],
    },
    {
      id: "css",
      title: "CSS",
      description: "Cascading Style Sheets - styling web pages",
      order: 3,
      subtopics: [
        {
          id: "css-flexbox-grid",
          title: "Flexbox & Grid",
          description: "Master modern CSS layout with Flexbox and Grid",
          order: 1,
          prerequisites: [],
          resources: [
            {
              type: "link",
              title: "CSS-Tricks: Complete Guide to Flexbox",
              url: "https://css-tricks.com/snippets/css/complete-guide-to-flexbox/",
            },
            {
              type: "link",
              title: "CSS-Tricks: Complete Guide to Grid",
              url: "https://css-tricks.com/snippets/css/complete-guide-grid/",
            },
          ],
          estimatedTime: "3 hours",
          difficulty: "beginner",
        },
        {
          id: "css-variables",
          title: "CSS Variables",
          description: "Use CSS custom properties for theming and dynamic styling",
          order: 2,
          prerequisites: ["css-flexbox-grid"],
          resources: [
            {
              type: "link",
              title: "MDN: Using CSS Custom Properties",
              url: "https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties",
            },
          ],
          estimatedTime: "1 hour",
          difficulty: "beginner",
        },
      ],
    },
    {
      id: "javascript",
      title: "JavaScript",
      description: "The programming language of the web",
      order: 4,
      subtopics: [],
    },
    {
      id: "typescript",
      title: "TypeScript",
      description: "Typed superset of JavaScript",
      order: 5,
      subtopics: [],
    },
    {
      id: "react",
      title: "React",
      description: "A JavaScript library for building user interfaces",
      order: 6,
      subtopics: [],
    },
    {
      id: "state-management",
      title: "State Management",
      description: "Managing application state effectively",
      order: 7,
      subtopics: [],
    },
    {
      id: "data-fetching-fundamentals",
      title: "Data Fetching Fundamentals",
      description: "Understanding how to fetch and handle data",
      order: 8,
      subtopics: [],
    },
    {
      id: "data-fetching-tools",
      title: "Data Fetching Tools",
      description: "Tools and libraries for data fetching",
      order: 9,
      subtopics: [],
    },
    {
      id: "tailwind",
      title: "Tailwind",
      description: "Utility-first CSS framework",
      order: 10,
      subtopics: [],
    },
    {
      id: "framer-motion",
      title: "Framer Motion",
      description: "Animation library for React",
      order: 11,
      subtopics: [],
    },
    {
      id: "nextjs",
      title: "Next.js",
      description: "React framework for production",
      order: 12,
      subtopics: [],
    },
    {
      id: "nodejs-fundamentals",
      title: "Node.js Fundamentals",
      description: "JavaScript runtime for server-side development",
      order: 13,
      subtopics: [],
    },
    {
      id: "expressjs",
      title: "Express.js",
      description: "Web application framework for Node.js",
      order: 14,
      subtopics: [],
    },
    {
      id: "databases",
      title: "Databases",
      description: "Understanding database systems and SQL",
      order: 15,
      subtopics: [],
    },
    {
      id: "orms",
      title: "ORMs",
      description: "Object-Relational Mapping tools",
      order: 16,
      subtopics: [],
    },
    {
      id: "caching",
      title: "Caching",
      description: "Caching strategies and implementations",
      order: 17,
      subtopics: [],
    },
    {
      id: "queues",
      title: "Queues",
      description: "Message queues and job processing",
      order: 18,
      subtopics: [],
    },
    {
      id: "security",
      title: "Security",
      description: "Web security best practices",
      order: 19,
      subtopics: [],
    },
    {
      id: "system-design",
      title: "System Design",
      description: "Designing scalable systems",
      order: 20,
      subtopics: [],
    },
    {
      id: "trpc",
      title: "tRPC",
      description: "End-to-end typesafe APIs",
      order: 21,
      subtopics: [],
    },
  ],
};

